### ISSUE TITLE
arm64 compatibility

### ISSUE THREAD

**Issue by mindfullsilence** [jagregory/cognito-local#142]
Well done on this package! Saving us a lot of headaches emulating cognito. 

Any chance of this docker image becoming compatible with arm64 architecture?

**Comment by jagregory** [comment]
Hey, glad to hear you're finding it useful 😄 

I'm definitely open to publishing an arm64 image, I just have to figure out how to do it and automate it in the pipeline. I don't have an arm compatible machine handy, so I might need your help to test the images. I'll give you a shout when I have something you can try.

**Comment by mindfullsilence** [comment]
Awesome, looking forward to it!

**Comment by jagregory** [comment]
Ok I think it's working now. If you could try pulling `jagregory/cognito-local:3.15.0` it should now be a multi-arch image with amd64 and arm64. Let me know if it works, thanks.

**Comment by jagregory** [comment]
Great, glad to hear it. Thanks for checking.
