### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by melih154** [jagregory/cognito-local#150]
Thanks for this great package. Helps a lot while working locally.

Latest package version on npm is v3.13.3, where as GitHub repo has latest version as v3.16.1. I am interested in AdminAddUserToGroup feature. Can you please publish latest version to npm as well? Thanks

**Comment by jagregory** [comment]
Ugh, thanks for spotting this! It looks like the automatic npm publish stopped working when I updated the pipeline for the multi-arch docker builds 🤦 

I'll take a look, thanks.

**Comment by jagregory** [comment]
Fixed, v3.16.2 is now available on npm and future releases will be too.
