### ISSUE TITLE
Is there a way to generate a 6-digit ConfirmationCode?

### ISSUE THREAD

**Issue by KeishiroKuma** [jagregory/cognito-local#192]
I am using cognito locally with this repository. 
However, I am having a little trouble because the ConfirmationCode is generated by default with 4 digits.
AWS cognito generates a 6-digit ConfirmationCode by default.
I would like to be able to generate a 6-digit confirmation code on the local machine as well.

Is there a way to do this or may I create a PR?

**Comment by jagregory** [comment]
That's definitely an oversight. Yes please submit a PR if you can, it should be a trivial change to the [OTP service](https://github.com/jagregory/cognito-local/blob/master/src/services/otp.ts).

**Comment by KeishiroKuma** [comment]
I just submitted a PR.
Will this modification be reflected in the image on DockerHub?

**Comment by jagregory** [comment]
Thanks for the PR. Yes, once merged a release will automatically be published (including a docker image).

**Comment by KeishiroKuma** [comment]
Thanks!
I hope the PR is correct.

**Comment by jagregory** [comment]
Your changes have been merged and released in [v3.16.3](https://github.com/jagregory/cognito-local/releases/tag/v3.16.3). You should be able to pull the `jagregory/cognito-local:3.16.3` Docker image now.

Thanks for the fix!

**Comment by KeishiroKuma** [comment]
Thank you very much for your quick response!
