### ISSUE TITLE
Feature request: populate defaults for `TokenValidityUnits` when unspecified by the end-user

### ISSUE THREAD

**Issue by RobHoman** [jagregory/cognito-local#220]
Hey @jagregory 

The `TokenValidityUnits` can be specified by the end-user in the inputs to the `CreateUserPoolClient` API request, and in this scenario it seems to me on a surface level that everything in cognito-local functions as expected.

In the scenario where the end-user does not specify `TokenValidityUnits` however, I think I am finding a mismatch in behavior. The `cognito-local` container leaves the units unset whereas production AWS cognito will set them to default values. It seems that units for `AccessToken` and `IdToken` defaults to `"hours"` whereas `RefreshToken` defaults to `"days"`

```
[TokenValidityUnits](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPoolClient.html#API_CreateUserPoolClient_RequestSyntax)

    The units in which the validity times are represented. The default unit for RefreshToken is days, and default for ID and access tokens are hours.

    Type: [TokenValidityUnitsType](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_TokenValidityUnitsType.html) object

    Required: No
```

Not too terribly difficult to work around this by explicitly setting the values. 

That being said, in the spirit of making the simulation match the behavior of production cognito, this would be a nice add!

Reference: https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPoolClient.html

Thanks for considering!

**Comment by jagregory** [comment]
Hey @RobHoman, I've published a fix for this. New clients now default to the unit values in the docs, and I also fixed the token generation so it actually uses the configured validity times too instead of just my hard-coded defaults.

**Comment by RobHoman** [comment]
Right on! Thanks.
