### ISSUE TITLE
[Bug] Tokens are generated before post-auth lambda executes

### ISSUE THREAD

**Issue by stocks29** [jagregory/cognito-local#281]
The initiate auth target currently generates tokens before the post-auth lambda is executed. This prevents any updates made in the post-auth lambda, like group changes, from being reflected in the generated tokens. Real cognito waits for the post-auth lambda to finish before it generates tokens.

**Comment by stocks29** [comment]
PR is up for this: https://github.com/jagregory/cognito-local/pull/282

**Comment by stocks29** [comment]
@jagregory would it be possible to get some of these fixes merged in and a new release created?

**Comment by jagregory** [comment]
Yep thanks @stocks29, I'll have a look.

I have no idea why but just for this repo I'm not getting notifications for Pull Requests, but I do when people tag me 🤷‍♂️  I need to dig through the notification settings.

**Comment by stocks29** [comment]
@jagregory , awesome, thank you sir!
