### ISSUE TITLE
Feature Request?: Flag to make verification codes predictable

### ISSUE THREAD

**Issue by paullallier** [jagregory/cognito-local#333]
Thank you very much for writing / sharing this - it looks like it potentially helps solves a gap in my CI/CD pipeline.

Since I'm planning to use it with automated tests, it would be really useful if there was a way to switch the confirmation codes to being predictable.  Presumably I'm not missing a feature that would allow this already?

If not, how about an environment variables "CODE=123456" - if present, all the confirmation code are set to 123456 (or whatever value is supplied)?  I might be able to have a go at implementing it, if it's a reasonable change, though my JS/TS is experience is almost zero.

**Comment by jagregory** [comment]
Ah, this is great. I was just starting to think how to solve this problem myself, and this is a very simple solution. I've merged your PR, thanks!
