### ISSUE TITLE
unable to change AuthFlow type to USER_PASSWORD_AUTH InitAuth with AuthFlow=USER_SRP_AUTH",

### ISSUE THREAD

**Issue by sanjayagnani92** [jagregory/cognito-local#339]
Hello all,
am using local Cognito to setup fields, able to register users while logging in 
getting AuthFlow is not supported
Have added USER_PASSWORD_AUTH in explicit auth flow 

`aws --endpoint http://localhost:9229 cognito-idp create-user-pool-client --user-pool-id local_6uohGxKl --client-name MyUserPool --explicit-auth-flow  USER_PASSWORD_AUTH 

this explicit-auth-flow isn't working 

Any suggestion or document pointing it or is it we need to change InitFlow?
`

**Comment by paullallier** [comment]
Looking at the docs for the aws cli, I think it's `--explicit-auth-flows` rather than `--explicit-auth-flow`.  Though I guess you just typed it wrong here?

**Comment by paullallier** [comment]
Oh, I guess the issue might be with how you are creating the users rather than the userpool.  Presumably you're using signUp or adminCreateUser?  Can you paste the code / command you're using for that?

**Comment by sanjayagnani92** [comment]
> Oh, I guess the issue might be with how you are creating the users rather than the userpool. Presumably you're using signUp or adminCreateUser? Can you paste the code / command you're using for that?

using Signup... poiting to local cognito setup/emulator

**Comment by paullallier** [comment]
I'm creating my client ID with a call to createUserPoolClient() using the PHP SDK, so my case is different, but working - so it's not fundamentally broken...

Presumably of you do this instead it still doesn't work?
`aws --endpoint http://localhost:9229/ cognito-idp create-user-pool-client --user-pool-id local_6uohGxKl --client-name MyUserPool --explicit-auth-flows USER_PASSWORD_AUTH`

**Comment by paullallier** [comment]
Oh, no.  I think it's `ALLOW_USER_PASSWORD_AUTH` rather than `USER_PASSWORD_AUTH`.

**Comment by sanjayagnani92** [comment]
> `ALLOW_USER_PASSWORD_AUTH`

checked with both the option didn't worked .


Scenario is able to create userPool and set configuration - even .cognito/db is proper 
Able to register user
on login request it gives 
`[1669337137748] ERROR: fe28128e NONE Cognito Local unsupported feature: InitAuth with AuthFlow=USER_SRP_AUTH {"reqId":"fe28128e"}`


even same is true on AWS servers if i disable SRP unable to login - over there only SRP based authentication works whereas in local this doesn't works

**Comment by sanjayagnani92** [comment]
Clear explict auth flows are just the setting which stats which kind of auth Flow that clientId can accept.
While making an login request authFlow needs to be set .. by default it is AUTH_SRP, for local it needs to be changed to
USER_AUTH_PASSWORD


`    newUser.setAuthenticationFlowType('USER_PASSWORD_AUTH');`

**Comment by paullallier** [comment]
In the PHP SDK, using adminIniitiateAuth(), I think I get the same errors as you if I set explicitly to the USER_SRP_AUTH flow rather than ADMIN_USER_PASSWORD_AUTH, so I suspect they issue you have is with the client rather than the server.

Looking at this issue (which was having the problem in the other direction), are you perhaps using authenticateUser() function (for the SRP flow) where you should be using iniitiateAuth() or adminIniitiateAuth()?
https://stackoverflow.com/questions/70601891/aws-cognito-custom-authentication-flow-initiateauth-giving-error

Other than that, I'm running out of ideas.
