### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by kadyrleev** [jagregory/cognito-local#34]
Thanks a lot for the effort!

Having a small issue here:
while Docker seems to be fine (getting some errors on API calls, but will try to figure out where the problem is), the local version run (_npx cognito-local_) fails with the following error:

```
node_modules/cognito-local/lib/bin/start.js:2
import { ConsoleLogger } from "../log";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

Cloning the repo, building and running also failed with _babel-node_ missing. Installing it didn't help much.
Is there anything I might miss on the system?

**Comment by kadyrleev** [comment]
Ended up with local docker setup.

**Comment by jagregory** [comment]
Thanks for raising this. I've obviously neglected this way of running the app, as I'm only using the docker image. I'll take a look, thanks.
