### ISSUE TITLE
getUserByUsername throws error if username contains dots (.)

### ISSUE THREAD

**Issue by kadyrleev** [jagregory/cognito-local#35]
I get this if username contains dots (.):
Error handling target: InitiateAuth Error: Can't run .value() on non-existant property of non-existant object. at StormDB2.value (/app/start.js:33848:19) at Object.get (/app/start.js:556061:104) at UserPoolClientService.getUserByUsername (/app/start.js:555742:49) at /app/start.js:556345:29

because StormDB uses dot-notation for a key in its get method:
https://github.com/TomPrograms/stormdb/blob/master/src/stormdb.js#L103

**Comment by jagregory** [comment]
Thanks. I'll put some tests in for different styles of usernames to prevent regressions like this in the future.

Looking at the code in stormdb it might just be the way we're calling get, it looks like the . parsing only kicks in if the key is a string.

**Comment by kadyrleev** [comment]
> Thanks. I'll put some tests in for different styles of usernames to prevent regressions like this in the future.
> 
> Looking at the code in stormdb it might just be the way we're calling get, it looks like the . parsing only kicks in if the key is a string.

Yep, it's applied to strings only.

It would be also good to test emails for usernames too as it is quite common scenario for Cognito.
Take a look at https://www.npmjs.com/package/faker - a really nice one for generating input data for tests.

And thanks again for your great work!
