### ISSUE TITLE
AdminCreateUser invalid response

### ISSUE THREAD

**Issue by kadyrleev** [jagregory/cognito-local#38]
AdminCreateUser target currently returns data in format as follows:
`{
    Username,
    Password,
    Attributes,
    Enabled,
    UserStatus,
    ConfirmationCode,
    UserCreateDate,
    UserLastModifiedDate
  }`
And thus result (for examples returned from PHP SDK) contains no data at all. Should be wrapped into 'User' as per docs:
> [
    'User' => [
        'Attributes' => [
            [
                'Name' => '<string>',
                'Value' => '<string>',
            ],
            // ...
        ],
        'Enabled' => true || false,
        'MFAOptions' => [
            [
                'AttributeName' => '<string>',
                'DeliveryMedium' => 'SMS|EMAIL',
            ],
            // ...
        ],
        'UserCreateDate' => <DateTime>,
        'UserLastModifiedDate' => <DateTime>,
        'UserStatus' => 'UNCONFIRMED|CONFIRMED|ARCHIVED|COMPROMISED|UNKNOWN|RESET_REQUIRED|FORCE_CHANGE_PASSWORD',
        'Username' => '<string>',
    ],
]

https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-cognito-idp-2016-04-18.html#admincreateuser
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminCreateUser-property

**Comment by jagregory** [comment]
Good catch. Thanks. I'll get this fixed ASAP.

**Comment by kadyrleev** [comment]
> Good catch. Thanks. I'll get this fixed ASAP.

We do thank you, mate! Cheers =)
