### ISSUE TITLE
[QUESTION] How to use lambda triggers?

### ISSUE THREAD

**Issue by WandersonAlves** [jagregory/cognito-local#43]
README says that `TriggerFunctions` is a `Record<string, string>`, but this string is a HTTP endpoint? File path of the handler?

Also, thanks for the project!

**Comment by jagregory** [comment]
Hey @WandersonAlves, it's just the function name. The readme does say that but perhaps it's not clear enough.

If you also use the `LambdaClient` config you can get cognito-local to invoke functions on your local machine too (e.g. if you're using serverless-offline or something similar).

For example, my config is:

```json
{
  "LambdaClient": {
    "endpoint": "http://host.docker.internal:3002"
  },
  "TriggerFunctions": {
    "CustomMessage": "cognito-custom-message",
    "PostConfirmation": "cognito-post-confirmation",
    "UserMigration": "cognito-user-migration"
  }
}
```

**Comment by jagregory** [comment]
I've updated the README to include a section on [how to use Lambda Triggers](https://github.com/jagregory/cognito-local#lambda-triggers), hopefully that helps future users. I'm going to close this issue now, but feel free to reopen if anything is still unclear.
