### ISSUE TITLE
Config options seemingly not being populated

### ISSUE THREAD

**Issue by Carrington** [jagregory/cognito-local#45]
Hello and thanks very much for your time and effort in this project!

I've got a bit of a stumper: I have the following config.json in .cognito as directed by the README:

```json
{
  "LambdaClient": {
    "credentials": {
      "accessKeyId": "local",
      "secretAccessKey": "local"
    },
    "region": "local"
  },
  "TokenConfig": {
    "IssuerDomain": "http://localhost:9229"
  },
  "TriggerFunctions": {},
  "UserPoolDefaults": {
    "Id": "us-east-1_xxxxxxxxx",
    "UsernameAttributes": ["email"],
    "MfaConfiguration": "ON"
  }
}
```
when I load up cognito-local, however, the user pool config that gets created is named 'undefined.json'. MFA is also not enabled during auth, even though I've edited the user pool options to this:
```
  "Options": {
    "MFAOptions": [
      "SMS"
    ],
    "UsernameAttributes": [
      "email",
      "email"
    ]
  }
  ```
  
Any insights you have would be helpful. I'm on Windows 10, Node 10.18.1

**Comment by sedhuait** [comment]
Hey @Carrington Were you able solve it? can please share a working `.cognito/db/$userPoolId.json` idpool config

**Comment by Carrington** [comment]
@sedhuait I'm afraid not. I don't think this repo is useable as a local emulator for a real cognito setup. Sorry to disappoint.

**Comment by jagregory** [comment]
@Carrington Sorry to hear you're having trouble. cognito-local does work, but as the readme says it's for a limited set of Cognito features that I'm personally using, anything outside of that is uncharted territory.

What are you doing with the pool once cognito-local has started? What API calls are you making against the pool?

**Comment by sedhuait** [comment]
Yes its working for me.. I just forked it to make it work for my use cases with my own docker image.

**Comment by jagregory** [comment]
No response, closing. Please re-open if needed.

**Comment by sedhuait** [comment]
https://github.com/sedhuait/cognito-local/commit/0d603d7e12bcb6c84af64be7aece9956da2b1369#diff-971637d96d35f6340524535e2fc62c59186e6bc1c3f1d28361f60ef9f9ed3833 

@jagregory Thanks a lot for ur work. I just added to support few custom parameters
