### ISSUE TITLE
[Question] Sample content for `.cognito/db/$userPoolId.json`

### ISSUE THREAD

**Issue by sedhuait** [jagregory/cognito-local#53]
Kindly share a sample content for `.cognito/db/$userPoolId.json`..

I just cloned to config.json it doesn't work.

**Comment by sedhuait** [comment]
If I leave it as empty i get resource not found execption.

**Comment by jagregory** [comment]
Thanks for the question. I should really have an example for this in the readme, or a way to create the pools using the API...

I think this should be the minimum you need for a pool to work:

```json
{
  "Users": {},
  "Options": {
    "Id": "your user pool id",
  }
}
```
